CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    priority INTEGER NOT NULL,
    description TEXT,
    deliverydate DATE NOT NULL 
);

CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectID INTEGER REFERENCES projects(id)
);

INSERT INTO projects (name, priority, description, deliverydate) 
    VALUES ('Make a web app', 1, 'Using JS', '2021-11-22');

INSERT INTO projects (name, priority, description, deliverydate) 
    VALUES ('Make a website', 2, 'HTML, CSS and JavaScript', '2021-11-25');

INSERT INTO projects (name, priority, description, deliverydate) 
    VALUES ('Make a desktop app', 3, 'Using Electron', '2021-11-29');

-- INSERT TASKS DATA
INSERT INTO tasks ( name, done, projectID) VALUES ('Download VueJS', false, 1);
INSERT INTO tasks ( name, done, projectID) VALUES ('Make it responsive', false, 2);
INSERT INTO tasks ( name, done, projectID) VALUES ('Design UI', false, 1);